### ISSUE TITLE
Ability to copy text

### ISSUE THREAD

**Issue by user1823** [elementdavv/chaka#1]
Please add the ability to copy text from PDFs.

**Comment by elementdavv** [comment]
The app only view a pdf file. It can't do copy or paste.

**Comment by user1823** [comment]
But why? I don't know of any other document viewer that doesn't allow copying text.

**Comment by elementdavv** [comment]
> But why? I don't know of any other document viewer that doesn't allow copying text.

MuPDF has another app that can edit.

**Comment by user1823** [comment]
Which one?

By the way, copying is not the same as editing. Copying text is a very basic feature that every document viewer should have.

**Comment by danpeig** [comment]
Please include this feature. I know MuPDF lacks it and this is why I never used it.

**Comment by elementdavv** [comment]
Ok I will add copy requirement to todo list.

**Comment by inattentive-nerd** [comment]
For the time being, you can use MJ PDF.
https://gitlab.com/mudlej_android/mj_pdf_reader
