### ISSUE TITLE
What do the buttons in the top bar do?

### ISSUE THREAD

**Issue by user1823** [elementdavv/chaka#2]
It is not clear what the buttons in the top bar do. You can make it clearer by adding a tooltip that appears on long pressing the button.

**Comment by elementdavv** [comment]
You could try every button to see what happens. Or watch the demo video provided.

**Comment by user1823** [comment]
Version [1.24.8a.5](https://github.com/elementdavv/chaka/releases/tag/v1.24.8a.5) includes tooltips. Thanks!
