### ISSUE TITLE
Text is blurred

### ISSUE THREAD

**Issue by user1823** [elementdavv/chaka#3]
In the latest version of the app (v1.24.8a.5), the text in the PDFs is slightly blurred.

When the same PDF is viewed in MuPDF viewer (v1.24.8a), the text is sharp and clear.

**Comment by user1823** [comment]
@elementdavv, would you please have a look at this issue?

**Comment by elementdavv** [comment]
Ok. I'll look at it.

**Comment by user1823** [comment]
Fixed in [v1.24.8a.7](https://github.com/elementdavv/chaka/releases/tag/v1.24.8a.7). Thanks!
