### ISSUE TITLE
Improve indentation in ToC

### ISSUE THREAD

**Issue by user1823** [elementdavv/chaka#4]
In the ToC, the subsections are indented. However, if the name of the subsection is long, it flows into the next line and this next line is not indented.

<img width=300 src="https://github.com/user-attachments/assets/417146a2-b4aa-450b-bbec-851ea6157ee9">

For e.g., in the above image, the readability will be improved if the words "Infectious", "Community-", "Health Care", "Diseases" started at the same level as the word "SECTION".

**Comment by elementdavv** [comment]
Indent added in v1.24.9a.8.

**Comment by user1823** [comment]
Thanks
